orbs:
  gcp-gcr: circleci/gcp-gcr@0.14.1
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: myContext
          image: python-flask-image
          registry-url: us.gcr.io
          filters:
            branches:
              only:
                main