version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.14.1

jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: python-flask-image
          no_output_timeout: 20m
          registry-url: gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: python-flask-image
          registry-url: gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  commit:
    jobs:
      - build-and-push