version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  build:
    docker:
      key: *cache_key

workflows:
  build-and-deploy:
    jobs:
      - build
      - gcp-gcr/build-and-push-image:
          requires:
            - build
          image: python-flask-image
          filters:
            branches:
              only:
                master